### ISSUE TITLE
希望出一个ubuntu的版本

### ISSUE THREAD

**Issue by LzVae** [hijkpw/scripts#1]
希望出一个ubuntu的版本，v2ray带伪装的一键脚本

**Comment by hijkpw** [comment]
已收到，我会尽量这两天出一个适用于ubuntu tls版本的一键脚本

**Comment by LzVae** [comment]
thx

**Comment by hijkpw** [comment]
@LzVae 已完成，请看readme文档，有问题随时留言

**Comment by LzVae** [comment]
执行报错：
...
确认满足按y，按其他退出脚本：y                                                                                                     
请输入您的主机名：xxx                                                                                        
请输入伪装路径，以/开头：/xxx                                                                                       
/dev/fd/63: line 90: nginx: command not found                                                                        
更新系统...                                                                                                              
Hit:1 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu xenial InRelease                                          
Hit:2 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu xenial-updates InRelease                                  
Hit:3 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu xenial-backports InRelease                                
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                    
Hit:5 http://archive.canonical.com/ubuntu xenial InRelease                                                           
Reading package lists... Done                                                                                        
Building dependency tree                                                                                             
Reading state information... Done                                                                                    
9 packages can be upgraded. Run 'apt list --upgradable' to see them.                                                 
Reading package lists... Done                                                                                        
Building dependency tree                                                                                             
Reading state information... Done                                                                                    
6.04.12 [244 kB]                                                                                                     
Setting up libatomic1:amd64 (5.4.0-6ubuntu1~16.04.12) ...                                                            
Get:5 http://asia-northeast1.gce.archive.ubuntu.com/ubuntu xenial/main amd64 crda amd64 3.13-1 [60.5 kB]             
0 upgraded, 13 newly installed, 0 to remove and 0 not upgraded.                                                      
kB]                                                                                                                  
ERROR: pyopenssl 19.1.0 has requirement cryptography>=2.8, but you'll have cryptography 1.2.3 which is incompatible. 
Installing collected packages: pytz, distro, parsedatetime, pyrfc3339, ConfigArgParse, zope.interface, zope.proxy, zo
pe.deferredimport, zope.deprecation, zope.event, zope.hookable, zope.component, mock, PyOpenSSL, requests-toolbelt, j
osepy, acme, certbot, ndg-httpsclient                                                                                
Successfully installed ConfigArgParse-1.0 PyOpenSSL-19.1.0 acme-1.2.0 certbot-1.2.0 distro-1.4.0 josepy-1.3.0 mock-3.
0.5 ndg-httpsclient-0.5.1 parsedatetime-2.5 pyrfc3339-1.1 pytz-2019.3 requests-toolbelt-0.9.1 zope.component-4.6 zope
.deferredimport-4.3.1 zope.deprecation-4.4.0 zope.event-4.4 zope.hookable-5.0.0 zope.interface-4.7.1 zope.proxy-4.3.3
                                                                                                                     
Traceback (most recent call last):                                                                                   
  File "/usr/local/bin/certbot", line 5, in <module>                                                                 
    from certbot.main import main                                                                                    
  File "/usr/local/lib/python3.5/dist-packages/certbot/main.py", line 2, in <module>                                 
    from certbot._internal import main as internal_main                                                              
  File "/usr/local/lib/python3.5/dist-packages/certbot/_internal/main.py", line 10, in <module>                      
    import josepy as jose                                                                                            
  File "/usr/local/lib/python3.5/dist-packages/josepy/__init__.py", line 44, in <module>                             
    from josepy.interfaces import JSONDeSerializable                                                                 
  File "/usr/local/lib/python3.5/dist-packages/josepy/interfaces.py", line 7, in <module>                            
    from josepy import errors, util                                                                                  
  File "/usr/local/lib/python3.5/dist-packages/josepy/util.py", line 7, in <module>                                  
    import OpenSSL                                                                                                   
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/__init__.py", line 8, in <module>                             
    from OpenSSL import crypto, SSL                                                                                  
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/crypto.py", line 15, in <module>                              
    from OpenSSL._util import (                                                                                      
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/_util.py", line 152, in <module>                              
    with ffi.from_buffer(b""):                                                                                       
TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object   
 获取证书失败，请到 https://www.hijk.pw 反馈

**Comment by hijkpw** [comment]
pip uninstall pyOpenSSL cryptography
sudo pip install pyOpenSSL cryptography

先执行这两个命令，然后再运行一键脚本

**Comment by LzVae** [comment]
卸载的时候报错了，sudo pip install 也是一样的报错，重新执行脚本也是一样的报错
root@instance-7:~# pip uninstall pyOpenSSL cryptography
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/uninstall.py", line 9, in <module>
    from pip._internal.cli.req_command import SessionCommandMixin
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/crypto.py", line 15, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/_util.py", line 152, in <module>
    with ffi.from_buffer(b""):
TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object
root@instance-7:~#

**Comment by hijkpw** [comment]
`pip3 uninstall pyOpenSSL cryptography`
`pip3 install pyOpenSSL cryptography`

用这个

**Comment by LzVae** [comment]
还是一样的

**Comment by LzVae** [comment]
root@instance-7:~# pip3 uninstall pyOpenSSL cryptography
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/commands/uninstall.py", line 9, in <module>
    from pip._internal.cli.req_command import SessionCommandMixin
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/req_command.py", line 15, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/index/collector.py", line 12, in <module>
    from pip._vendor import html5lib, requests
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/requests/__init__.py", line 97, in <module>
    from pip._vendor.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python3.5/dist-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/crypto.py", line 15, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python3.5/dist-packages/OpenSSL/_util.py", line 152, in <module>
    with ffi.from_buffer(b""):
TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object
root@instance-7:~#

**Comment by LzVae** [comment]
ssh root@34.85.2.12
password:zxd,.!123
您可以看一下

**Comment by hijkpw** [comment]
已收到，信息删了吧

**Comment by hijkpw** [comment]
你的系统中存在一个孤零零的pip3，不知道怎么来的，那个pip3的环境是错误的，无法安装和卸载任何包

我现在已经修复了你的pip3环境，你再试试
